service: uipath-job-status-listener

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  environment:
    language: ${file(config.json):language}

plugins:
  - serverless-python-requirements

functions:
  job-status:
    handler: handler.handler
    environment:
      secret: ${file(config.json):orchestrator.secret}
    events:
      - http:
          path: job-status
          method: post
