service: uipath-job-status-listener

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  environment:
    language: ${file(config.json):language}
    orchestrator_secret: ${file(config.json):orchestrator.secret}

plugins:
  - serverless-python-requirements

functions:
  chatwork:
    handler: handler.chatwork
    environment:
      api_token: ${file(config.json):notification.chatwork.api_token}
      room_id: ${file(config.json):notification.chatwork.room_id}
    events:
      - http:
          path: job-status/chatwork
          method: post

  google_hangouts:
    handler: handler.google_hangouts
    environment:
      incomming_webhook_url: ${file(config.json):notification.google_hangouts.incomming_webhook_url}
    events:
      - http:
          path: job-status/google_hangouts
          method: post

  slack:
    handler: handler.slack
    environment:
      incomming_webhook_url: ${file(config.json):notification.slack.incomming_webhook_url}
    events:
      - http:
          path: job-status/slack
          method: post