service: uipath-job-status-listener

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  environment:
    language: ${file(config.json):language}

plugins:
  - serverless-python-requirements

functions:
  webhook_backlog:
    handler: webhook_handler.backlog
    environment:
      orchestrator_secret: ${file(config.json):webhook.orchestrator.secret}
      api_key: ${file(config.json):webhook.backlog.api_key}
      space_key: ${file(config.json):webhook.backlog.space_key}
      project_id: ${file(config.json):webhook.backlog.project_id}      
      issue_type_id: ${file(config.json):webhook.backlog.issue_type_id}
    events:
      - http:
          path: job-status/backlog
          method: post

  webhook_chatwork:
    handler: webhook_handler.chatwork
    environment:
      orchestrator_secret: ${file(config.json):webhook.orchestrator.secret}
      api_token: ${file(config.json):webhook.chatwork.api_token}
      room_id: ${file(config.json):webhook.chatwork.room_id}
    events:
      - http:
          path: job-status/chatwork
          method: post

  webhook_google_hangouts:
    handler: webhook_handler.google_hangouts
    environment:
      orchestrator_secret: ${file(config.json):webhook.orchestrator.secret}
      incomming_webhook_url: ${file(config.json):webhook.google_hangouts.incomming_webhook_url}
    events:
      - http:
          path: job-status/google_hangouts
          method: post

  webhook_slack:
    handler: webhook_handler.slack
    environment:
      orchestrator_secret: ${file(config.json):webhook.orchestrator.secret}
      incomming_webhook_url: ${file(config.json):webhook.slack.incomming_webhook_url}
    events:
      - http:
          path: job-status/slack
          method: post

  scheduled_backlog:
    handler: scheduled_handler.backlog
    environment:
      orchestrator_url: ${file(config.json):scheduled.orchestrator.url}
      orchestrator_tenancy_name: ${file(config.json):scheduled.orchestrator.tenancy_name}
      orchestrator_username: ${file(config.json):scheduled.orchestrator.username}
      orchestrator_password: ${file(config.json):scheduled.orchestrator.password}
      orchestrator_api_key: ${file(config.$son):scheduled.orchestrator.api_key}
      orchestrator_ntlm_authentication: ${file(config.json):scheduled.orchestrator.ntlm_authentication}
      interval: ${file(config.json):scheduled.chatwork.interval}
      api_key: ${file(config.json):webhook.backlog.api_key}
      space_key: ${file(config.json):webhook.backlog.space_key}
      project_id: ${file(config.json):webhook.backlog.project_id}      
      issue_type_id: ${file(config.json):webhook.backlog.issue_type_id}
    events:
      - schedule: ${file(config.json):scheduled.backlog.schedule}

  scheduled_chatwork:
    handler: scheduled_handler.chatwork
    environment:
      orchestrator_url: ${file(config.json):scheduled.orchestrator.url}
      orchestrator_tenancy_name: ${file(config.json):scheduled.orchestrator.tenancy_name}
      orchestrator_username: ${file(config.json):scheduled.orchestrator.username}
      orchestrator_password: ${file(config.json):scheduled.orchestrator.password}
      orchestrator_api_key: ${file(config.$son):scheduled.orchestrator.api_key}
      orchestrator_ntlm_authentication: ${file(config.json):scheduled.orchestrator.ntlm_authentication}
      interval: ${file(config.json):scheduled.chatwork.interval}
      api_token: ${file(config.json):scheduled.chatwork.api_token}
      room_id: ${file(config.json):scheduled.chatwork.room_id}
    events:
      - schedule: ${file(config.json):scheduled.chatwork.schedule}

  scheduled_google_hangouts:
    handler: scheduled_handler.google_hangouts
    environment:
      orchestrator_url: ${file(config.json):scheduled.orchestrator.url}
      orchestrator_tenancy_name: ${file(config.json):scheduled.orchestrator.tenancy_name}
      orchestrator_username: ${file(config.json):scheduled.orchestrator.username}
      orchestrator_password: ${file(config.json):scheduled.orchestrator.password}
      orchestrator_api_key: ${file(config.$son):scheduled.orchestrator.api_key}
      orchestrator_ntlm_authentication: ${file(config.json):scheduled.orchestrator.ntlm_authentication}
      interval: ${file(config.json):scheduled.google_hangouts.interval}
      incomming_webhook_url: ${file(config.json):webhook.google_hangouts.incomming_webhook_url}
    events:
      - schedule: ${file(config.json):scheduled.google_hangouts.schedule}

  scheduled_slack:
    handler: scheduled_handler.slack
    environment:
      orchestrator_url: ${file(config.json):scheduled.orchestrator.url}
      orchestrator_tenancy_name: ${file(config.json):scheduled.orchestrator.tenancy_name}
      orchestrator_username: ${file(config.json):scheduled.orchestrator.username}
      orchestrator_password: ${file(config.json):scheduled.orchestrator.password}
      orchestrator_api_key: ${file(config.$son):scheduled.orchestrator.api_key}
      orchestrator_ntlm_authentication: ${file(config.json):scheduled.orchestrator.ntlm_authentication}
      interval: ${file(config.json):scheduled.slack.interval}
      incomming_webhook_url: ${file(config.json):scheduled.slack.incomming_webhook_url}
    events:
      - schedule: ${file(config.json):scheduled.slack.schedule}
